parameters:
#    scriptorium_user_script.example.class: scriptorium\UserScriptBundle\Example

services:
#    scriptorium_user_script.example:
#        class: %scriptorium_user_script.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
